apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: sonar-pvc
    namespace: commons
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a8fd266e65bc9063
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  volumeMode: Filesystem